"""init

Revision ID: 3547c014fcab
Revises: 
Create Date: 2026-01-31 22:04:15.547126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3547c014fcab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('human_player', sa.Integer(), nullable=False),
    sa.Column('bot_player', sa.Integer(), nullable=False),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_player', sa.Integer(), nullable=False),
    sa.Column('terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('hand_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('final_pot', sa.Float(), nullable=True),
    sa.Column('final_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('hand_id', sa.UUID(), nullable=False),
    sa.Column('action_index', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('legal_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('current_bet', sa.Integer(), nullable=False),
    sa.Column('num_raises', sa.Integer(), nullable=False),
    sa.Column('state_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    op.drop_table('hands')
    op.drop_table('games')
    # ### end Alembic commands ###
